"""add_lawyer_marketplace_models

Revision ID: 105360236f9d
Revises: 
Create Date: 2026-04-01 21:08:59.577843

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '105360236f9d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lawyer_specialisations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_lawyer_specialisations_slug'), 'lawyer_specialisations', ['slug'], unique=True)
    op.create_table('lawyer_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('bar_number', sa.String(length=100), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('years_experience', sa.Integer(), nullable=True),
    sa.Column('languages', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('emirate', sa.String(length=50), nullable=True),
    sa.Column('consultation_fee_aed', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('hourly_rate_aed', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('whatsapp', sa.String(length=30), nullable=True),
    sa.Column('office_address', sa.Text(), nullable=True),
    sa.Column('contact_unlock_credits', sa.Integer(), nullable=False),
    sa.Column('response_time_hours', sa.Integer(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('profile_views', sa.Integer(), nullable=False),
    sa.Column('total_unlocks', sa.Integer(), nullable=False),
    sa.Column('average_rating', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('review_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lawyer_profiles_user_id'), 'lawyer_profiles', ['user_id'], unique=True)
    op.create_table('lawyer_bookings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('lawyer_profile_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('credits_charged', sa.Integer(), nullable=False),
    sa.Column('contact_unlocked_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(), nullable=True),
    sa.Column('cancelled_by', sa.String(length=20), nullable=True),
    sa.Column('client_note', sa.Text(), nullable=True),
    sa.Column('admin_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lawyer_profile_id'], ['lawyer_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_id', 'lawyer_profile_id', name='uq_booking_client_lawyer')
    )
    op.create_index(op.f('ix_lawyer_bookings_client_id'), 'lawyer_bookings', ['client_id'], unique=False)
    op.create_index(op.f('ix_lawyer_bookings_lawyer_profile_id'), 'lawyer_bookings', ['lawyer_profile_id'], unique=False)
    op.create_table('lawyer_profile_specialisations',
    sa.Column('lawyer_profile_id', sa.Integer(), nullable=False),
    sa.Column('specialisation_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['lawyer_profile_id'], ['lawyer_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['specialisation_id'], ['lawyer_specialisations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('lawyer_profile_id', 'specialisation_id')
    )
    op.create_table('lawyer_reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=False),
    sa.Column('lawyer_profile_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('is_visible', sa.Boolean(), nullable=False),
    sa.Column('lawyer_reply', sa.Text(), nullable=True),
    sa.Column('lawyer_reply_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['lawyer_bookings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['client_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lawyer_profile_id'], ['lawyer_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('booking_id')
    )
    op.create_index(op.f('ix_lawyer_reviews_client_id'), 'lawyer_reviews', ['client_id'], unique=False)
    op.create_index(op.f('ix_lawyer_reviews_lawyer_profile_id'), 'lawyer_reviews', ['lawyer_profile_id'], unique=False)
    op.create_index(op.f('ix_users_reset_token'), 'users', ['reset_token'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_reset_token'), table_name='users')
    op.drop_index(op.f('ix_lawyer_reviews_lawyer_profile_id'), table_name='lawyer_reviews')
    op.drop_index(op.f('ix_lawyer_reviews_client_id'), table_name='lawyer_reviews')
    op.drop_table('lawyer_reviews')
    op.drop_table('lawyer_profile_specialisations')
    op.drop_index(op.f('ix_lawyer_bookings_lawyer_profile_id'), table_name='lawyer_bookings')
    op.drop_index(op.f('ix_lawyer_bookings_client_id'), table_name='lawyer_bookings')
    op.drop_table('lawyer_bookings')
    op.drop_index(op.f('ix_lawyer_profiles_user_id'), table_name='lawyer_profiles')
    op.drop_table('lawyer_profiles')
    op.drop_index(op.f('ix_lawyer_specialisations_slug'), table_name='lawyer_specialisations')
    op.drop_table('lawyer_specialisations')
    # ### end Alembic commands ###
