"""expand_lawyer_marketplace_schema

Revision ID: 98dbf6e68b2c
Revises: 105360236f9d
Create Date: 2026-04-01 21:26:24.722515

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '98dbf6e68b2c'
down_revision: Union[str, Sequence[str], None] = '105360236f9d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lawyer_bookings', sa.Column('credit_log_id', sa.Integer(), nullable=True))
    op.add_column('lawyer_bookings', sa.Column('source_category_slug', sa.String(length=80), nullable=True))
    op.add_column('lawyer_bookings', sa.Column('source_question_id', sa.Integer(), nullable=True))
    op.add_column('lawyer_bookings', sa.Column('contact_method_chosen', sa.String(length=20), nullable=True))
    op.add_column('lawyer_bookings', sa.Column('lawyer_responded_at', sa.DateTime(), nullable=True))
    op.add_column('lawyer_bookings', sa.Column('cancellation_reason', sa.Text(), nullable=True))
    op.create_foreign_key(None, 'lawyer_bookings', 'credit_logs', ['credit_log_id'], ['id'])
    op.create_foreign_key(None, 'lawyer_bookings', 'questions', ['source_question_id'], ['id'])
    op.drop_column('lawyer_bookings', 'admin_note')
    op.add_column('lawyer_profiles', sa.Column('display_name', sa.String(length=150), nullable=True))
    op.add_column('lawyer_profiles', sa.Column('bar_issuing_authority', sa.String(length=200), nullable=True))
    op.add_column('lawyer_profiles', sa.Column('licence_pdf_path', sa.String(length=500), nullable=True))
    op.add_column('lawyer_profiles', sa.Column('photo_path', sa.String(length=500), nullable=True))
    op.add_column('lawyer_profiles', sa.Column('firm_name', sa.String(length=200), nullable=True))
    op.add_column('lawyer_profiles', sa.Column('firm_website', sa.String(length=300), nullable=True))
    op.add_column('lawyer_profiles', sa.Column('sub_specialisations', postgresql.ARRAY(sa.String()), nullable=True))
    op.add_column('lawyer_profiles', sa.Column('courts_practiced_in', postgresql.ARRAY(sa.String()), nullable=True))
    op.add_column('lawyer_profiles', sa.Column('jurisdictions', postgresql.ARRAY(sa.String()), nullable=True))
    op.add_column('lawyer_profiles', sa.Column('consultation_modes', postgresql.ARRAY(sa.String()), nullable=True))
    op.add_column('lawyer_profiles', sa.Column('typical_response_hours', sa.Integer(), nullable=True))
    op.add_column('lawyer_profiles', sa.Column('offers_free_first_consultation', sa.Boolean(), nullable=True))
    op.add_column('lawyer_profiles', sa.Column('free_consultation_minutes', sa.Integer(), nullable=True))
    op.add_column('lawyer_profiles', sa.Column('initial_consultation_fee_aed', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('lawyer_profiles', sa.Column('fee_on_case_basis', sa.Boolean(), nullable=True))
    op.add_column('lawyer_profiles', sa.Column('fixed_fee_services', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('lawyer_profiles', sa.Column('pricing_note', sa.Text(), nullable=True))
    op.add_column('lawyer_profiles', sa.Column('contact_email', sa.String(length=255), nullable=True))
    op.add_column('lawyer_profiles', sa.Column('office_city', sa.String(length=100), nullable=True))
    op.add_column('lawyer_profiles', sa.Column('office_country', sa.String(length=100), nullable=True))
    op.add_column('lawyer_profiles', sa.Column('education', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('lawyer_profiles', sa.Column('certifications', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('lawyer_profiles', sa.Column('notable_cases', sa.Text(), nullable=True))
    op.add_column('lawyer_profiles', sa.Column('linkedin_url', sa.String(length=300), nullable=True))
    op.add_column('lawyer_profiles', sa.Column('website_url', sa.String(length=300), nullable=True))
    op.add_column('lawyer_profiles', sa.Column('total_completed_bookings', sa.Integer(), nullable=False))
    op.add_column('lawyer_profiles', sa.Column('total_reviews', sa.Integer(), nullable=False))
    op.add_column('lawyer_profiles', sa.Column('is_featured', sa.Boolean(), nullable=True))
    op.add_column('lawyer_profiles', sa.Column('verification_status', sa.String(length=20), nullable=False))
    op.add_column('lawyer_profiles', sa.Column('rejection_reason', sa.Text(), nullable=True))
    op.add_column('lawyer_profiles', sa.Column('admin_notes', sa.Text(), nullable=True))
    op.add_column('lawyer_profiles', sa.Column('verified_by_admin_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'lawyer_profiles', 'users', ['verified_by_admin_id'], ['id'])
    op.drop_column('lawyer_profiles', 'is_verified')
    op.drop_column('lawyer_profiles', 'consultation_fee_aed')
    op.drop_column('lawyer_profiles', 'review_count')
    op.drop_column('lawyer_profiles', 'response_time_hours')
    op.drop_column('lawyer_profiles', 'emirate')
    op.add_column('lawyer_reviews', sa.Column('would_recommend', sa.Boolean(), nullable=True))
    op.add_column('lawyer_reviews', sa.Column('lawyer_replied_at', sa.DateTime(), nullable=True))
    op.add_column('lawyer_reviews', sa.Column('hidden_reason', sa.Text(), nullable=True))
    op.add_column('lawyer_reviews', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.drop_column('lawyer_reviews', 'lawyer_reply_at')
    op.add_column('lawyer_specialisations', sa.Column('icon', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lawyer_specialisations', 'icon')
    op.add_column('lawyer_reviews', sa.Column('lawyer_reply_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('lawyer_reviews', 'updated_at')
    op.drop_column('lawyer_reviews', 'hidden_reason')
    op.drop_column('lawyer_reviews', 'lawyer_replied_at')
    op.drop_column('lawyer_reviews', 'would_recommend')
    op.add_column('lawyer_profiles', sa.Column('emirate', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('lawyer_profiles', sa.Column('response_time_hours', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('lawyer_profiles', sa.Column('review_count', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('lawyer_profiles', sa.Column('consultation_fee_aed', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
    op.add_column('lawyer_profiles', sa.Column('is_verified', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'lawyer_profiles', type_='foreignkey')
    op.drop_column('lawyer_profiles', 'verified_by_admin_id')
    op.drop_column('lawyer_profiles', 'admin_notes')
    op.drop_column('lawyer_profiles', 'rejection_reason')
    op.drop_column('lawyer_profiles', 'verification_status')
    op.drop_column('lawyer_profiles', 'is_featured')
    op.drop_column('lawyer_profiles', 'total_reviews')
    op.drop_column('lawyer_profiles', 'total_completed_bookings')
    op.drop_column('lawyer_profiles', 'website_url')
    op.drop_column('lawyer_profiles', 'linkedin_url')
    op.drop_column('lawyer_profiles', 'notable_cases')
    op.drop_column('lawyer_profiles', 'certifications')
    op.drop_column('lawyer_profiles', 'education')
    op.drop_column('lawyer_profiles', 'office_country')
    op.drop_column('lawyer_profiles', 'office_city')
    op.drop_column('lawyer_profiles', 'contact_email')
    op.drop_column('lawyer_profiles', 'pricing_note')
    op.drop_column('lawyer_profiles', 'fixed_fee_services')
    op.drop_column('lawyer_profiles', 'fee_on_case_basis')
    op.drop_column('lawyer_profiles', 'initial_consultation_fee_aed')
    op.drop_column('lawyer_profiles', 'free_consultation_minutes')
    op.drop_column('lawyer_profiles', 'offers_free_first_consultation')
    op.drop_column('lawyer_profiles', 'typical_response_hours')
    op.drop_column('lawyer_profiles', 'consultation_modes')
    op.drop_column('lawyer_profiles', 'jurisdictions')
    op.drop_column('lawyer_profiles', 'courts_practiced_in')
    op.drop_column('lawyer_profiles', 'sub_specialisations')
    op.drop_column('lawyer_profiles', 'firm_website')
    op.drop_column('lawyer_profiles', 'firm_name')
    op.drop_column('lawyer_profiles', 'photo_path')
    op.drop_column('lawyer_profiles', 'licence_pdf_path')
    op.drop_column('lawyer_profiles', 'bar_issuing_authority')
    op.drop_column('lawyer_profiles', 'display_name')
    op.add_column('lawyer_bookings', sa.Column('admin_note', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'lawyer_bookings', type_='foreignkey')
    op.drop_constraint(None, 'lawyer_bookings', type_='foreignkey')
    op.drop_column('lawyer_bookings', 'cancellation_reason')
    op.drop_column('lawyer_bookings', 'lawyer_responded_at')
    op.drop_column('lawyer_bookings', 'contact_method_chosen')
    op.drop_column('lawyer_bookings', 'source_question_id')
    op.drop_column('lawyer_bookings', 'source_category_slug')
    op.drop_column('lawyer_bookings', 'credit_log_id')
    # ### end Alembic commands ###
